### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by KingPanda68** [zuri-training/fetch_metadata-team_aardvark2#21]
Work on the authentication module of the platform.

**Comment by ArthurKingDev** [comment]
C:\Users\user\metafrom django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'index.html')

@login_required(login_url='login')
def support(request):
    return render(request, 'support.html')

@login_required(login_url='login')
def profile(request):
    return render(request, 'profile.html')

@login_required(login_url='login')
def profile(request):
    return render(request, 'profile.html')


def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        
        if password == password2:
            if User.objects.filter(email=email).exists():
                messages.info(request, 'Email Taken')
                return redirect('signup')
            elif User.objects.filter(username=username).exists():
                messages.info(request, 'Username Taken')
                return redirect('signup')
            else:
                user = User.objects.create_user(username=username, email=email, password=password)
                user.save()


#log user in and redirect to settings page
                user_login = auth.authenticate(username=username, password=password)
                auth.login(request, user_login)

                 
        else:
            messages.info(request, 'Password Do Not Match')
            return redirect('signup')
           
    return render(request, 'signup.html')



def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('dashboard')
        else:
           messages.info(request, 'Invalid Credentials') 
           return redirect('login')
    else:
        return render(request, 'login.html')

@login_required(login_url='login')
def dashboard(request):
    return render(request, 'dashboard.html')

@login_required(login_url='login')
def dashboard2(request):
    return render(request, 'dashboard2.html')


@login_required(login_url='login')
def password(request):
    return render(request, 'password.html')

@login_required(login_url='login')
def notification(request):
    return render(request, 'notification.html')

@login_required(login_url='login')
def security(request):
    return render(request, 'security.html')

@login_required(login_url='login')
def settings(request):
    return render(request, 'settings.html')
\fetch_metadata\venv\views.py
