### ISSUE TITLE
About and Profile Pages

### ISSUE THREAD

**Issue by KingPanda68** [zuri-training/fetch_metadata-team_aardvark2#5]
Attach a link to your Figma file containing the wireframes, Lo-Fi, and Hi-Fi of your assigned pages

**Comment by Realareta** [comment]
https://www.figma.com/file/Yi7SF1KSHfteKfDE0VHRyt/Profile-and-About-Us-Pages?node-id=0%3A1&t=QJZ6hc5Chu7lql8u-1
