### ISSUE TITLE
FAQ and Support Pages

### ISSUE THREAD

**Issue by KingPanda68** [zuri-training/fetch_metadata-team_aardvark2#6]
Attach a link to your Figma file containing the wireframes, Lo-Fi, and Hi-Fi of your assigned pages

**Comment by onifesimi** [comment]
https://www.figma.com/file/YWiWWJ3sdfaSXHjLTHTVro/LO-FI?node-id=0%3A1&t=o9HDtTvcVO3lgHMG-1https://www.figma.com/file/YWiWWJ3sdfaSXHjLTHTVro/LO-FI?node-id=0%3A1&t=o9HDtTvcVO3lgHMG-1
